### ISSUE TITLE
my-script

### ISSUE THREAD

**Issue by jayvdb** [TheWall89/inducoapi#2]
The entry point / script defined at https://github.com/TheWall89/inducoapi/blob/master/pyproject.toml#L21 is incorrect.

The result is:
```py
$ my-script
Traceback (most recent call last):
  File "/usr/bin/my-script", line 33, in <module>
    sys.exit(load_entry_point('inducoapi==2.0.0', 'console_scripts', 'my-script')())
  File "/usr/bin/my-script", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 173, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'inducoapi' has no attribute 'main'
```

**Comment by TheWall89** [comment]
Hello and thanks for the report. I'll try to look into this as soon as possible. (same as the other issue, but really thank you for taking the time to open an issue :smile: )

**Comment by TheWall89** [comment]
Hi, get latest version from `master` branch and this should be fixed. Sorry, forgot to create a PR and just did a commit/push.
Feel free to re-open if not working.
